title: J. Nick Seymour
description: Theatre and Media Professional
url: https://jnickseymour.github.io/
logo: Seymour.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
